This script calculates the accessibilty for each green area

### 0. Libraries

In [ ]:
import geopandas as gpd
import pandas as pd

### 1. Accessibility

In [2]:
# load the file
access_ga = gpd.read_file("D:/Climate_Shelter_Index/isocrona/access_green/access_green.shp")

In [4]:
access_ga.head()

                        nome     bicycle   highway                   geometry
0  G.NO PADRE GIOVANNI BREVI  designated  cycleway  POINT (11.36948 44.49722)
1  G.NO PADRE GIOVANNI BREVI         NaN   footway  POINT (11.37207 44.49604)
2  G.NO PADRE GIOVANNI BREVI         NaN   footway  POINT (11.37171 44.49571)
3  G.NO PADRE GIOVANNI BREVI         NaN   footway  POINT (11.37205 44.49601)
4  G.NO PADRE GIOVANNI BREVI         NaN   footway  POINT (11.37222 44.49614)

#### 1.1 Cycleway

In [4]:
# Identify cycleway
cycleway = access_ga[access_ga['highway']=='cycleway']
cycleway.head()

                         nome     bicycle   highway                   geometry
0   G.NO PADRE GIOVANNI BREVI  designated  cycleway  POINT (11.36948 44.49722)
5   G.NO PADRE GIOVANNI BREVI  designated  cycleway  POINT (11.36807 44.49774)
21     GIARDINO YITZHAK RABIN  designated  cycleway  POINT (11.35959 44.52870)
22     GIARDINO YITZHAK RABIN  designated  cycleway  POINT (11.35992 44.52828)
23     GIARDINO YITZHAK RABIN  designated  cycleway  POINT (11.36120 44.52942)

In [5]:
# Create a DataFrame to store the aggregation
sum_cycleway = cycleway[['nome', 'highway']].copy()
# Count the occurrences of each 'nome'
sum_cycleway['n_cycleway'] = sum_cycleway.groupby('nome')['nome'].transform('count')

sum_cycleway.head()

                         nome   highway  n_cycleway
0   G.NO PADRE GIOVANNI BREVI  cycleway           2
5   G.NO PADRE GIOVANNI BREVI  cycleway           2
21     GIARDINO YITZHAK RABIN  cycleway           3
22     GIARDINO YITZHAK RABIN  cycleway           3
23     GIARDINO YITZHAK RABIN  cycleway           3

In [6]:
# Drop duplicates to keep only unique rows
sum_cycleway = sum_cycleway.drop_duplicates(subset=['nome', 'highway', 'n_cycleway'])
sum_cycleway.head()

                          nome   highway  n_cycleway
0    G.NO PADRE GIOVANNI BREVI  cycleway           2
21      GIARDINO YITZHAK RABIN  cycleway           3
25             PARCO DEI CEDRI  cycleway          13
98          PARCO DEI GIARDINI  cycleway           2
170       PERCORSO LUNGONAVILE  cycleway          39

In [18]:
sum_cycleway.to_csv(r'D:\Climate_Shelter_Index\isocrona\sum_cycleway.csv', index=False)

#### 1.2 Footway

In [67]:
# Identify street accessible by foot
footway= access_ga[(access_ga['highway']=='footway')]
footway.head()

                        nome bicycle  highway                   geometry
1  G.NO PADRE GIOVANNI BREVI     NaN  footway  POINT (11.37207 44.49604)
2  G.NO PADRE GIOVANNI BREVI     NaN  footway  POINT (11.37171 44.49571)
3  G.NO PADRE GIOVANNI BREVI     NaN  footway  POINT (11.37205 44.49601)
4  G.NO PADRE GIOVANNI BREVI     NaN  footway  POINT (11.37222 44.49614)
6  G.NO PADRE GIOVANNI BREVI     NaN  footway  POINT (11.37151 44.49569)

In [68]:
# Create a DataFrame to store the aggregation
sum_footway = footway[['nome', 'highway']].copy()
# Count the occurrences of each 'nome'
sum_footway['n_footway'] = sum_footway.groupby('nome')['nome'].transform('count')

sum_footway.head()

                        nome  highway  n_footway
1  G.NO PADRE GIOVANNI BREVI  footway         12
2  G.NO PADRE GIOVANNI BREVI  footway         12
3  G.NO PADRE GIOVANNI BREVI  footway         12
4  G.NO PADRE GIOVANNI BREVI  footway         12
6  G.NO PADRE GIOVANNI BREVI  footway         12

In [69]:
# Drop duplicates to keep only unique rows
sum_footway = sum_footway.drop_duplicates(subset=['nome', 'highway', 'n_footway'])
sum_footway.head()

                                    nome  highway  n_footway
1              G.NO PADRE GIOVANNI BREVI  footway         12
16                      G.NO DIANA SABBI  footway          2
18  ASILO NIDO PRIMAVERA (GIA  TORRETTA)  footway          1
20                GIARDINO ALBERTO SITTA  footway          1
32                       PARCO DEI CEDRI  footway          7

In [70]:
sum_footway.to_csv(r'D:\Climate_Shelter_Index\isocrona\sum_footway.csv', index=False)

#### 1.3 Footway + Cycleway

In [71]:
# Load  files
cycleway_csv = pd.read_csv(r'D:\Climate_Shelter_Index\isocrona\sum_cycleway.csv')
footway_csv = pd.read_csv(r'D:\Climate_Shelter_Index\isocrona\sum_footway.csv')
green_areas = gpd.read_file(r"D:\Climate_Shelter_Index\green_areas__ndvi.shp")
green_areas.head(3)

,quart,nome,ubicazione,classe_uni,classe_gia,classe_pen,classe_suo,area_prato,area_ug,data_agg,...,zona_pross,area_Ha,d_fountain,id_df,picnic_tab,id_pt,benches,id_bench,NDVI,geometry
0,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,9509.007,12461.168,2009-01-29,...,OSSERVANZA - PADERNO,0.950901,no,N/A,no,N/A,no,N/A,0.542155,"POLYGON ((11.31509 44.42248, 11.31511 44.42256..."
1,Santo Stefano,GIARDINO MONUMENTO CADUTI DI SABBIUNO,Via di Sabbiuno,PARCO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,5514.205,6730.89,2009-01-29,...,OSSERVANZA - PADERNO,0.551420,no,N/A,no,N/A,no,N/A,0.459359,"POLYGON ((11.31288 44.42104, 11.31289 44.42109..."
2,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,16811.194,24817.745,2007-03-13,...,OSSERVANZA - PADERNO,1.681119,no,N/A,no,N/A,no,N/A,0.624308,"POLYGON ((11.31463 44.42146, 11.31496 44.42149..."

In [73]:
# Merge the shapefile with the DataFrame about cycleway based on the 'nome' column
merged_df = green_areas.merge(cycleway_csv[['nome', 'n_cycleway']], on='nome', how='left')
# Convert 'n_footway' to integers and fill missing values with 0
merged_df['n_cycleway'] = merged_df['n_cycleway'].fillna(0).astype(int)

In [74]:
# Merge the shapefile with the DataFrame about footway based on the 'nome' column
merged_df = merged_df.merge(footway_csv[['nome', 'n_footway']], on='nome', how='left')
# Convert 'n_footway' to integers and fill missing values with 0
merged_df['n_footway'] = merged_df['n_footway'].fillna(0).astype(int)

In [75]:
merged_df.head()

,quart,nome,ubicazione,classe_uni,classe_gia,classe_pen,classe_suo,area_prato,area_ug,data_agg,...,d_fountain,id_df,picnic_tab,id_pt,benches,id_bench,NDVI,geometry,n_cycleway,n_footway
0,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,9509.007,12461.168,2009-01-29,...,no,N/A,no,N/A,no,N/A,0.542155,"POLYGON ((11.31509 44.42248, 11.31511 44.42256...",0,0
1,Santo Stefano,GIARDINO MONUMENTO CADUTI DI SABBIUNO,Via di Sabbiuno,PARCO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,5514.205,6730.89,2009-01-29,...,no,N/A,no,N/A,no,N/A,0.459359,"POLYGON ((11.31288 44.42104, 11.31289 44.42109...",0,0
2,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,16811.194,24817.745,2007-03-13,...,no,N/A,no,N/A,no,N/A,0.624308,"POLYGON ((11.31463 44.42146, 11.31496 44.42149...",0,0
3,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,87.272,6250.574,2007-09-20,...,no,N/A,no,N/A,no,N/A,0.877684,"POLYGON ((11.32362 44.45097, 11.32372 44.45110...",0,8
4,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,-4.817,21360.397,2007-09-20,...,no,N/A,no,N/A,no,N/A,0.879811,"POLYGON ((11.32160 44.45340, 11.32164 44.45341...",0,8

In [77]:
# Save the shapefile
merged_df.to_file(r'D:\Climate_Shelter_Index\isocrona\green_area_accessibility.shp')

#### 1.4 Footway + cycleway + bus stop

In [26]:
# Load  files
bus_5min = pd.read_csv('D:/Climate_Shelter_Index/isocrona/sum_bus_5_stop.csv')
bus_10min = pd.read_csv('D:/Climate_Shelter_Index/isocrona/sum_bus_10_stop.csv')
accessibility_ga = gpd.read_file('D:/Climate_Shelter_Index/isocrona/green_area_accessibility.shp')

In [27]:
bus_10min.shape

(409, 3)

In [81]:
# rename columns
bus_5min = bus_5min.rename(columns= {'n_busstop':'busstop5'})
bus_10min = bus_10min.rename(columns= {'n_busstop':'busstop10'})

In [82]:
## 5 min
# Merge the shapefile DataFrame with the CSV DataFrame based on the 'nome' column
merged_df = accessibility_ga.merge(bus_5min[['nome', 'busstop5']], on='nome', how='left')

# Convert 'busstop5' to integers and fill missing values with 0
merged_df['busstop5'] = merged_df['busstop5'].fillna(0).astype(int)

In [83]:
## 10 min
# Merge the shapefile DataFrame with the CSV DataFrame based on the 'nome' column
merged_df = merged_df.merge(bus_10min[['nome', 'busstop10']], on='nome', how='left')

# Convert 'busstop5' to integers and fill missing values with 0
merged_df['busstop10'] = merged_df['busstop10'].fillna(0).astype(int)

In [84]:
merged_df.head()

,quart,nome,ubicazione,classe_uni,classe_gia,classe_pen,classe_suo,area_prato,area_ug,data_agg,...,picnic_tab,id_pt,benches,id_bench,NDVI,n_cycleway,n_footway,geometry,busstop5,busstop10
0,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,9509.007,12461.168,2009-01-29,...,no,N/A,no,N/A,0.542155,0,0,"POLYGON ((11.31509 44.42248, 11.31511 44.42256...",2,3
1,Santo Stefano,GIARDINO MONUMENTO CADUTI DI SABBIUNO,Via di Sabbiuno,PARCO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,5514.205,6730.89,2009-01-29,...,no,N/A,no,N/A,0.459359,0,0,"POLYGON ((11.31288 44.42104, 11.31289 44.42109...",0,0
2,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,16811.194,24817.745,2007-03-13,...,no,N/A,no,N/A,0.624308,0,0,"POLYGON ((11.31463 44.42146, 11.31496 44.42149...",2,3
3,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,87.272,6250.574,2007-09-20,...,no,N/A,no,N/A,0.877684,0,8,"POLYGON ((11.32362 44.45097, 11.32372 44.45110...",3,8
4,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,-4.817,21360.397,2007-09-20,...,no,N/A,no,N/A,0.879811,0,8,"POLYGON ((11.32160 44.45340, 11.32164 44.45341...",3,8

In [85]:
# Save the shapefile
merged_df.to_file(r'D:\Climate_Shelter_Index\isocrona\green_area_accessibility_bus.shp')

#### 1.5 Footway + cycleway + bus stop + disabled parking

In [29]:
# Load  files
disab_parking = pd.read_csv('D:/Climate_Shelter_Index/isocrona/disabled_parking.csv')
accessibility_bus_ga = gpd.read_file('D:/Climate_Shelter_Index/isocrona/green_area_accessibility_bus.shp')

In [30]:
disab_parking

                                                  nome  disab_p_5
0                                 AIUOLA VIA ALTOBELLI         12
1                                        AIUOLE  DANTI          5
2                                     AIUOLE  RAMENGHI          9
3                                          AIUOLE AIMO         19
4          AIUOLE COMPARTO BECCACCINO LA PIRA CAPITINI         19
..                                                 ...        ...
404              VERDE CONDOMINIO VIA GALEAZZA 14 - 28          2
405  VERDE PASOLINI - ORTI (EX GIARDINO P. P. PASOL...          8
406                               VERDE SPONDA RUZZOLA          7
407                          VIALE FELSINA-VICOLO NERO          1
408                                VILLA GUASTAVILLANI          0

[409 rows x 2 columns]

In [31]:
# Merge the shapefile DataFrame with the GeoDataFrame based on the 'nome' column
merged_df = accessibility_bus_ga.merge(disab_parking, on='nome', how='left')

In [33]:
# Convert 'disabled_p' to integers and fill missing values with 0
merged_df['disab_p_5'] = merged_df['disab_p_5'].fillna(0).astype(int)

In [43]:
# Replace 0 with -1 in the 'disab_p_5' column to assign a negative value if there no disabled parking
merged_df['disab_p_5'] = merged_df['disab_p_5'].replace(0, -1)

In [45]:
merged_df.head()

,quart,nome,ubicazione,classe_uni,classe_gia,classe_pen,classe_suo,area_prato,area_ug,data_agg,...,id_pt,benches,id_bench,NDVI,n_cycleway,n_footway,busstop5,busstop10,geometry,disab_p_5
0,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,9509.007,12461.168,2009-01-29,...,N/A,no,N/A,0.542155,0,0,2,3,"POLYGON ((11.31509 44.42248, 11.31511 44.42256...",-1
1,Santo Stefano,GIARDINO MONUMENTO CADUTI DI SABBIUNO,Via di Sabbiuno,PARCO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,5514.205,6730.89,2009-01-29,...,N/A,no,N/A,0.459359,0,0,0,0,"POLYGON ((11.31288 44.42104, 11.31289 44.42109...",-1
2,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,16811.194,24817.745,2007-03-13,...,N/A,no,N/A,0.624308,0,0,2,3,"POLYGON ((11.31463 44.42146, 11.31496 44.42149...",-1
3,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,87.272,6250.574,2007-09-20,...,N/A,no,N/A,0.877684,0,8,3,8,"POLYGON ((11.32362 44.45097, 11.32372 44.45110...",-1
4,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,-4.817,21360.397,2007-09-20,...,N/A,no,N/A,0.879811,0,8,3,8,"POLYGON ((11.32160 44.45340, 11.32164 44.45341...",-1

In [46]:
# Save the shapefile
merged_df.to_file(r'D:\Climate_Shelter_Index\isocrona\complete_accessibility')

### 2. Index of Accessibility
Consider some aspects to calculate the index: 
- the park is accessible via a foot path (how many accesses?)
- the park is accessible via a bike path (how many accesses?)
- the park has a bus stop nearby (how many bus stop within a 5-minute walk? or 10 minute walk?)
- the park has a disabled parking nearby (how many disabled parking within a 5-minute walk?)

In [50]:
# Load file
complete_accessibility = gpd.read_file('D:/Climate_Shelter_Index/isocrona/complete_accessibility/complete_accessibility.shp')

In [52]:
# Define the weights for each aspect
weight_cycleway = 0.3
weight_footway = 0.3
weight_busstop5 = 0.2
weight_busstop10 = 0.1
weight_disabled_parking = 0.1

In [53]:
# Normalize and calculate the accessibility index for each aspect
def normalize_and_calculate_index(col_name, weight):
    min_value = complete_accessibility[col_name].min()
    max_value = complete_accessibility[col_name].max()
    normalized_value = (complete_accessibility[col_name] - min_value) / (max_value - min_value)
    return normalized_value * weight

In [54]:
# Calculate the accessibility index for each aspect
complete_accessibility['index_n_cycleway'] = normalize_and_calculate_index('n_cycleway', weight_cycleway)
complete_accessibility['index_n_footway'] = normalize_and_calculate_index('n_footway', weight_footway)
complete_accessibility['index_busstop5'] = normalize_and_calculate_index('busstop5', weight_busstop5)
complete_accessibility['index_busstop10'] = normalize_and_calculate_index('busstop10', weight_busstop10)
complete_accessibility['index_disab_p_5'] = normalize_and_calculate_index('disab_p_5', weight_disabled_parking)

In [55]:
# Calculate the total_accessibility_index
complete_accessibility['access_ind'] = complete_accessibility[['index_n_cycleway', 'index_n_footway', 'index_busstop5', 'index_busstop10', 'index_disab_p_5']].sum(axis=1)

In [56]:
# Remove the individual index columns
complete_accessibility.drop(columns=['index_n_cycleway', 'index_n_footway', 'index_busstop5', 'index_busstop10', 'index_disab_p_5'], inplace=True)

In [60]:
complete_accessibility.head()

,quart,nome,ubicazione,classe_uni,classe_gia,classe_pen,classe_suo,area_prato,area_ug,data_agg,...,benches,id_bench,NDVI,n_cycleway,n_footway,busstop5,busstop10,disab_p_5,geometry,access_ind
0,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,9509.007,12461.168,2009-01-29,...,no,N/A,0.542155,0,0,2,3,-1,"POLYGON ((11.31509 44.42248, 11.31511 44.42256...",0.012821
1,Santo Stefano,GIARDINO MONUMENTO CADUTI DI SABBIUNO,Via di Sabbiuno,PARCO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,5514.205,6730.89,2009-01-29,...,no,N/A,0.459359,0,0,0,0,-1,"POLYGON ((11.31288 44.42104, 11.31289 44.42109...",0.000000
2,Santo Stefano,PARCO DEI CALANCHI DI SABBIUNO,Via di Sabbiuno,PARCO ESTENSIVO,SOMMITALE,0 -20%,ARGILLOSO COMPATTO,16811.194,24817.745,2007-03-13,...,no,N/A,0.624308,0,0,2,3,-1,"POLYGON ((11.31463 44.42146, 11.31496 44.42149...",0.012821
3,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,87.272,6250.574,2007-09-20,...,no,N/A,0.877684,0,8,3,8,-1,"POLYGON ((11.32362 44.45097, 11.32372 44.45110...",0.071077
4,Santo Stefano,PARCO PADERNO,Via Paderno,PARCO ESTENSIVO,PIANO,20 - 40%,MEDIO IMPASTO,-4.817,21360.397,2007-09-20,...,no,N/A,0.879811,0,8,3,8,-1,"POLYGON ((11.32160 44.45340, 11.32164 44.45341...",0.071077

In [61]:
complete_accessibility.shape

(930, 32)

In [62]:
# Save the shapefile
complete_accessibility.to_file(r'D:\Climate_Shelter_Index\isocrona\access_index')